import type { PlanDefinition } from './types';

// FRANTIC: A swarm of agents hit the fab at once—ASML + TSMC + NVIDIA joint push for +12.8% OEE.
// Early phase: no deps, maximal parallelism. Later: fan‑in, tighter coupling, and pile‑on.
export const franticPlan: PlanDefinition = {
  name: 'Frantic',
  description:
    'Hectic, all‑at‑once optimization sprint across ASML lithography cells and the TSMC line, with NVIDIA co‑optimization. Objective: +12.8% end‑to‑end efficiency (OEE) without yield regressions.',
  groups: [
    { id: 'P', title: 'Frantic Launch — Parallel Scouts & Knobs', description: 'Spin up dozens of agents immediately. No dependencies. Find knobs, bottlenecks, and quick wins.' },
    { id: 'B', title: 'Litho Line & Process Modules', description: 'Upgrade EUV/DUV stages, materials, and flows. Converge to stable recipes.' },
    { id: 'E', title: 'Metrology, Yield, Reliability', description: 'Measure everything: overlay, CDU, stochastic defects, parametrics. Lock in gains.' },
    { id: 'D', title: 'Rollout & Volume Ramp', description: 'Gate the changes, scale to multiple lines, hold the +12.8% under real load.' },
  ],
  items: [
    // -----------------------------
    // P — FRANTIC PARALLEL (no deps)
    // -----------------------------
    { id: 'P01', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Map OEE tree: availability, performance, quality. Flag top 20 micro‑losses.' },
    { id: 'P02', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'EUV dose stability scout: source power drift & fast feedback hooks.' },
    { id: 'P03', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Track time‑in‑state by tool; extract idle, warmup, recipe changeover.' },
    { id: 'P04', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'FOUP logistics blitz: AGV routing, queue discipline, buffer sizing.' },
    { id: 'P05', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Mask shop handshake: write slots, blank quality, pellicle lead times.' },
    { id: 'P06', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'OPC/ILT compute surge: cluster sizing; job packing; cache strategy.' },
    { id: 'P07', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Reticle contamination watch: clean intervals vs. throughput hit.' },
    { id: 'P08', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Stage vibration survey: floor spectra, tool isolators, acoustic cross‑talk.' },
    { id: 'P09', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Resist supply & track uptime: bake plate MTBF, coat/develop takt.' },
    { id: 'P10', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Scrap pareto: stochastic defects, scumming, particles, overlay outliers.' },
    { id: 'P11', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Recipe changeover tax: lens conditioning and reticle swaps.' },
    { id: 'P12', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'Inline metrology latency: sampling plan vs. queue time penalty.' },
    { id: 'P13', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle transmittance audit; thermal bow risk at high EUV dose.' },
    { id: 'P14', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Lens contamination model: outgassing sources and clean triggers.' },
    { id: 'P15', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'TSMC line balance scan: bottleneck hop between litho and etch.' },
    { id: 'P16', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'NVIDIA DFM rule refresh: hotspot library & acceptable waivers.' },
    { id: 'P17', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Scribe‑line monitor plan: add overlay & CD sentinels early.' },
    { id: 'P18', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'WIP cap policy variants: Little’s Law sanity across tools.' },
    { id: 'P19', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Reticle heating model: dose vs. pattern density vs. overlay drift.' },
    { id: 'P20', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'EUV source warm‑start script to shave morning loss minutes.' },
    { id: 'P21', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Tool matching target: overlay & CDU deltas normalized across twins.' },
    { id: 'P22', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Chamber particle audit: purge rates, door cycles, FOUP seals.' },
    { id: 'P23', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Operator motion study: micro‑delays during reticle swaps.' },
    { id: 'P24', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Downtime taxonomy cleanup: better codes → better actions.' },
    { id: 'P25', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Photoresist bake optimization: plate temp uniformity scan.' },
    { id: 'P26', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 15000, tps_min: 30, tps_max: 90, work_desc: 'Developer nozzle calibration; rinse sequence variants.' },
    { id: 'P27', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Track‑to‑scanner handshake latencies; handshake retries.' },
    { id: 'P28', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Reticle carrier health check; latch sensors; foam wear.' },
    { id: 'P29', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Overlay feedback loop mapping: controller gains by product.' },
    { id: 'P30', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle frame warp survey; clamp torque standards.' },
    { id: 'P31', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Mask blank inspection slots; defect spec alignment with OPC.' },
    { id: 'P32', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Throughput model v0: takt by layer; Monte Carlo day plan.' },
    { id: 'P33', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'EUV collector reflectivity watch; clean/no‑clean decision rules.' },
    { id: 'P34', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'NVIDIA co‑design channel: ECO queue, hotspot reproducer kits.' },
    { id: 'P35', group: 'P', sector: 'PLANNING', depends_on: [], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Quality firewall: fast binning to quarantine suspect lots.' },

    // -----------------------------
    // B — MODULE UPGRADES (early B items still parallel, then pile‑on)
    // -----------------------------
    { id: 'B01', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Dose control retune: faster PID; guardrail limits.' },
    { id: 'B02', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Stage feed‑forward: mark‑to‑mark predictive overlay nudge.' },
    { id: 'B03', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Auto‑reticle‑clamp verification and torque logging.' },
    { id: 'B04', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle heater profile to limit bow under high dose.' },
    { id: 'B05', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Track recipe presets for rapid product switching.' },
    { id: 'B06', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'OPC cache warmups for recurring masks; hash‑based reuse.' },
    { id: 'B07', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'EUV source warm‑start automation (from P20) hardened.' },
    { id: 'B08', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Resist prime nozzle quick‑check; self‑cal scheduler.' },
    { id: 'B09', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'AGV dispatch rules: short‑cycle boost without starvation.' },
    { id: 'B10', group: 'B', sector: 'BUILD', depends_on: [], estimate_ms: 15000, tps_min: 30, tps_max: 90, work_desc: 'Lens purge routine timings to cut changeover deadtime.' },

    // pile‑on begins — link back to P‑findings
    { id: 'B11', group: 'B', sector: 'BUILD', depends_on: ['P06'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'OPC/ILT scheduling: preemption policy for critical layers.' },
    { id: 'B12', group: 'B', sector: 'BUILD', depends_on: ['P29'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Overlay controller gain sweep per product family.' },
    { id: 'B13', group: 'B', sector: 'BUILD', depends_on: ['P21', 'B12'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Tool matching pass: align twins to golden overlay/CDU.' },
    { id: 'B14', group: 'B', sector: 'BUILD', depends_on: ['P14'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Lens contam mitigation kit: new purge & bake sequences.' },
    { id: 'B15', group: 'B', sector: 'BUILD', depends_on: ['P25', 'P26'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Track temp uniformity fix; cure bake drift.' },
    { id: 'B16', group: 'B', sector: 'BUILD', depends_on: ['P31'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Mask blank spec check integration before OPC launch.' },
    { id: 'B17', group: 'B', sector: 'BUILD', depends_on: ['P07', 'B03'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Reticle clean cadence auto‑planner.' },
    { id: 'B18', group: 'B', sector: 'BUILD', depends_on: ['P08'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Under‑tool acoustic damping panels.' },
    { id: 'B19', group: 'B', sector: 'BUILD', depends_on: ['P27'], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Track‑scanner handshake retry backoff tuning.' },
    { id: 'B20', group: 'B', sector: 'BUILD', depends_on: ['P18', 'P32'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'WIP caps per cell; throughput optimizer online.' },
    { id: 'B21', group: 'B', sector: 'BUILD', depends_on: ['P33'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Collector clean decision engine (reflectivity trending).' },
    { id: 'B22', group: 'B', sector: 'BUILD', depends_on: ['P30'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle clamp torque SOP & sensorized wrench rollout.' },
    { id: 'B23', group: 'B', sector: 'BUILD', depends_on: ['P22'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Door cycle purge & FOUP seal refresh kit.' },
    { id: 'B24', group: 'B', sector: 'BUILD', depends_on: ['P15', 'B20'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Line rebalance: relieve etch wait after litho speedups.' },
    { id: 'B25', group: 'B', sector: 'BUILD', depends_on: ['P17'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Scribe‑line monitor masks—spin into next lots.' },
    { id: 'B26', group: 'B', sector: 'BUILD', depends_on: ['P10'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Stochastic defect guardband tweak; resist/filter updates.' },
    { id: 'B27', group: 'B', sector: 'BUILD', depends_on: ['P34'], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'NVIDIA hotspot repro kits shipped to litho cells.' },
    { id: 'B28', group: 'B', sector: 'BUILD', depends_on: ['B21', 'B14'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'EUV uptime kit install window (collector + purge).' },
    { id: 'B29', group: 'B', sector: 'BUILD', depends_on: ['P12'], estimate_ms: 15000, tps_min: 30, tps_max: 90, work_desc: 'Inline metrology fast path; sampling plan v2.' },
    { id: 'B30', group: 'B', sector: 'BUILD', depends_on: ['P24'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Downtime code UI revamp; single‑click root cause.' },
    { id: 'B31', group: 'B', sector: 'BUILD', depends_on: ['P23'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Reticle swap kitting: pre‑staged tools & carriers.' },
    { id: 'B32', group: 'B', sector: 'BUILD', depends_on: ['P28'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Carrier latch sensor replacement & predictive alerts.' },
    { id: 'B33', group: 'B', sector: 'BUILD', depends_on: ['P02', 'B01'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Dose drift auto‑correct per wafer map.' },
    { id: 'B34', group: 'B', sector: 'BUILD', depends_on: ['P19', 'B12'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Reticle heating compensation in overlay model.' },
    { id: 'B35', group: 'B', sector: 'BUILD', depends_on: ['P05', 'P31'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Mask shop SLA tweak & auto‑paging for write slot slips.' },
    { id: 'B36', group: 'B', sector: 'BUILD', depends_on: ['B20', 'B24'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Takt re‑calc after rebalance; redistribute FOUP buffers.' },
    { id: 'B37', group: 'B', sector: 'BUILD', depends_on: ['B06'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'OPC artifact cache eviction policy tuned for hit‑rate.' },
    { id: 'B38', group: 'B', sector: 'BUILD', depends_on: ['B05', 'P11'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Changeover recipe packer: minimal lens conditioning.' },
    { id: 'B39', group: 'B', sector: 'BUILD', depends_on: ['B13'], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'Golden‑tool ghosting: push matching params to twins.' },
    { id: 'B40', group: 'B', sector: 'BUILD', depends_on: ['B33', 'B29'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Closed‑loop CDU + dose trim by layer.' },

    // -----------------------------
    // E — METROLOGY / YIELD / RELIABILITY (fan‑in on B)
    // -----------------------------
    { id: 'E01', group: 'E', sector: 'EVAL', depends_on: ['B12', 'B13'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Overlay nm regression across tools; post‑matching check.' },
    { id: 'E02', group: 'E', sector: 'EVAL', depends_on: ['B40'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'CDU maps before/after dose trim; guardband impact.' },
    { id: 'E03', group: 'E', sector: 'EVAL', depends_on: ['B26'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Stochastic defect rate trend; wafer‑level heatmaps.' },
    { id: 'E04', group: 'E', sector: 'EVAL', depends_on: ['B14', 'B21'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Uptime delta from contam mitigations; MTBF delta.' },
    { id: 'E05', group: 'E', sector: 'EVAL', depends_on: ['B28'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Collector clean windows vs. OEE; find sweet spot.' },
    { id: 'E06', group: 'E', sector: 'EVAL', depends_on: ['B22'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle clamp torque → overlay drift study.' },
    { id: 'E07', group: 'E', sector: 'EVAL', depends_on: ['B37'], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'OPC cache hit‑rate vs. mask turn time & compute cost.' },
    { id: 'E08', group: 'E', sector: 'EVAL', depends_on: ['B36'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Line balance validation: no new downstream starvation.' },
    { id: 'E09', group: 'E', sector: 'EVAL', depends_on: ['B20'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'WIP cap A/B outcomes: cycle‑time vs. throughput.' },
    { id: 'E10', group: 'E', sector: 'EVAL', depends_on: ['B33'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Dose auto‑correct stability vs. noise injection.' },
    { id: 'E11', group: 'E', sector: 'EVAL', depends_on: ['B29'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Metrology latency cut: feedback timeliness to litho.' },
    { id: 'E12', group: 'E', sector: 'EVAL', depends_on: ['B24'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Fab‑wide takt audit post‑rebalance.' },
    { id: 'E13', group: 'E', sector: 'EVAL', depends_on: ['B31'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Reticle swap time variance reduction check.' },
    { id: 'E14', group: 'E', sector: 'EVAL', depends_on: ['B19'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Handshake retry incidence; wafer delay histogram shift.' },
    { id: 'E15', group: 'E', sector: 'EVAL', depends_on: ['B18'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Vibration spectral change → overlay & CDU correlation.' },
    { id: 'E16', group: 'E', sector: 'EVAL', depends_on: ['B05', 'B38'], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'Changeover overhead drop measured across product mix.' },
    { id: 'E17', group: 'E', sector: 'EVAL', depends_on: ['B25'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'New scribe‑line monitors sensitivity/false positive rate.' },
    { id: 'E18', group: 'E', sector: 'EVAL', depends_on: ['B35'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Mask SLA → litho wait time impact; days‑to‑recover.' },
    { id: 'E19', group: 'E', sector: 'EVAL', depends_on: ['B23'], estimate_ms: 15000, tps_min: 30, tps_max: 90, work_desc: 'Particle excursion rate before/after FOUP seal refresh.' },
    { id: 'E20', group: 'E', sector: 'EVAL', depends_on: ['B39'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Ghosting efficacy: twin drift after push.' },
    { id: 'E21', group: 'E', sector: 'EVAL', depends_on: ['B10'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Changeover deadtime cut quantified.' },
    { id: 'E22', group: 'E', sector: 'EVAL', depends_on: ['B01', 'B33'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Dose stability → CDU & yield uplift curve.' },
    { id: 'E23', group: 'E', sector: 'EVAL', depends_on: ['B07'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Warm‑start success rate; morning startup minutes saved.' },
    { id: 'E24', group: 'E', sector: 'EVAL', depends_on: ['B22', 'B34'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle torque + heating compensation residuals.' },
    { id: 'E25', group: 'E', sector: 'EVAL', depends_on: ['B04'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Bow under dose test; transmittance change vs. time.' },
    { id: 'E26', group: 'E', sector: 'EVAL', depends_on: ['B08', 'B15'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Track stability & defectivity metrics post tune.' },
    { id: 'E27', group: 'E', sector: 'EVAL', depends_on: ['B20', 'B36'], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Fab‑level OEE recompute—target +12.8% proof.' },
    { id: 'E28', group: 'E', sector: 'EVAL', depends_on: ['B30'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Root‑cause tagging completeness & actionability audit.' },
    { id: 'E29', group: 'E', sector: 'EVAL', depends_on: ['B27'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'NVIDIA hotspot closure stats; ECO loop time.' },
    { id: 'E30', group: 'E', sector: 'EVAL', depends_on: ['B24', 'B36'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Downstream (etch/met) wait time regression check.' },

    // -----------------------------
    // D — ROLLOUT / VOLUME RAMP
    // -----------------------------
    { id: 'D01', group: 'D', sector: 'DEPLOY', depends_on: ['E27'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Go/No‑Go gate for fab‑wide rollout (+12.8% confirmed).' },
    { id: 'D02', group: 'D', sector: 'DEPLOY', depends_on: ['E01', 'E02'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Overlay/CDU control plan baselined per product.' },
    { id: 'D03', group: 'D', sector: 'DEPLOY', depends_on: ['E11', 'E28'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'New downtime codes + dashboards to ops.' },
    { id: 'D04', group: 'D', sector: 'DEPLOY', depends_on: ['E23'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Morning warm‑start SOP push; training completed.' },
    { id: 'D05', group: 'D', sector: 'DEPLOY', depends_on: ['E05', 'E24'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Collector & pellicle maintenance windows codified.' },
    { id: 'D06', group: 'D', sector: 'DEPLOY', depends_on: ['E09', 'E12'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'WIP cap & line balance policies live in scheduler.' },
    { id: 'D07', group: 'D', sector: 'DEPLOY', depends_on: ['E03', 'E26'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Defectivity guardbands updated; release notes to QA.' },
    { id: 'D08', group: 'D', sector: 'DEPLOY', depends_on: ['E29'], estimate_ms: 15000, tps_min: 30, tps_max: 90, work_desc: 'NVIDIA ECO fast lane formalized; artifact kits versioned.' },
    { id: 'D09', group: 'D', sector: 'DEPLOY', depends_on: ['E06'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle torque tools & logging issued to all shifts.' },
    { id: 'D10', group: 'D', sector: 'DEPLOY', depends_on: ['E14'], estimate_ms: 18000, tps_min: 30, tps_max: 90, work_desc: 'Handshake retry alarm thresholds tuned in MES.' },
    { id: 'D11', group: 'D', sector: 'DEPLOY', depends_on: ['E08'], estimate_ms: 23000, tps_min: 30, tps_max: 90, work_desc: 'Downstream readiness checklists to avoid moving bottlenecks.' },
    { id: 'D12', group: 'D', sector: 'DEPLOY', depends_on: ['E20'], estimate_ms: 21000, tps_min: 30, tps_max: 90, work_desc: 'Golden‑tool push cadence & audit trail.' },
    { id: 'D13', group: 'D', sector: 'DEPLOY', depends_on: ['E27'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Public KPI: OEE delta and yield neutrality published internally.' },
    { id: 'D14', group: 'D', sector: 'DEPLOY', depends_on: ['E15'], estimate_ms: 19000, tps_min: 30, tps_max: 90, work_desc: 'Acoustic/vibration mitigations standardized in facility SOP.' },
    { id: 'D15', group: 'D', sector: 'DEPLOY', depends_on: ['E18'], estimate_ms: 24000, tps_min: 30, tps_max: 90, work_desc: 'Mask SLA contract updates; paging & penalties enabled.' },
    { id: 'D16', group: 'D', sector: 'DEPLOY', depends_on: ['E21'], estimate_ms: 17000, tps_min: 30, tps_max: 90, work_desc: 'Changeover playbook laminated at toolside.' },
    { id: 'D17', group: 'D', sector: 'DEPLOY', depends_on: ['E19'], estimate_ms: 16000, tps_min: 30, tps_max: 90, work_desc: 'FOUP seal spare kits stocked; PM calendar set.' },
    { id: 'D18', group: 'D', sector: 'DEPLOY', depends_on: ['E25'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Pellicle heating watchpoints integrated into shift checks.' },
    { id: 'D19', group: 'D', sector: 'DEPLOY', depends_on: ['E30', 'E12'], estimate_ms: 22000, tps_min: 30, tps_max: 90, work_desc: 'Cross‑module drumbeat: hold no new queues downstream.' },
    { id: 'D20', group: 'D', sector: 'DEPLOY', depends_on: ['D01', 'D11', 'D19'], estimate_ms: 20000, tps_min: 30, tps_max: 90, work_desc: 'Multi‑line rollout; sustain +12.8% for 30 days; lock and handoff.' },
  ],
};

export default franticPlan;
